# Generated by Django 3.1.4 on 2020-12-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_man',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_woman',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=30, verbose_name='gender :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='data'),
        ),
    ]
