# Generated by Django 3.1.4 on 2020-12-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='caregory_images', verbose_name='Image: ')),
                ('is_main', models.BooleanField(default=False, verbose_name='esas')),
                ('is_sub', models.BooleanField(default=False, verbose_name='orta')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('is_position', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('m', 'middle'), ('no', 'none')], max_length=50, verbose_name='is position')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('price', models.FloatField(verbose_name='price')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='Image: ')),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=20, verbose_name='size: ')),
                ('color_name', models.CharField(max_length=20, verbose_name='color')),
                ('code', models.CharField(max_length=30, verbose_name='urun kodu')),
                ('content', models.CharField(max_length=30, verbose_name='urun iceriyi')),
                ('fit', models.CharField(max_length=30, verbose_name='fit')),
                ('sezon', models.CharField(max_length=30, verbose_name='sezon')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='product.category')),
                ('color', models.ManyToManyField(blank=True, related_name='color_id', to='product.Product')),
            ],
            options={
                'verbose_name': 'mehsul',
                'verbose_name_plural': 'mehsullar',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=True, verbose_name='esas')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Image: ')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pro_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_id', to='product.product')),
            ],
            options={
                'verbose_name': 'sekil',
                'verbose_name_plural': 'sekiller',
                'db_table': ' image',
            },
        ),
    ]
