# Generated by Django 3.1.4 on 2020-12-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201220_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_id', to='product.Category'),
        ),
    ]
