# Generated by Django 3.1.4 on 2020-12-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201222_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active_class',
            field=models.BooleanField(default=False, verbose_name='esas'),
        ),
    ]
