# Generated by Django 3.1.4 on 2020-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_is_active_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_category',
            field=models.ManyToManyField(blank=True, related_name='related_categories', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active_class',
            field=models.BooleanField(default=False, verbose_name='yasil reng'),
        ),
    ]
