# Generated by Django 3.1.4 on 2021-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210103_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Image'),
        ),
        migrations.AlterModelTable(
            name='productimg',
            table='image',
        ),
    ]
