# Generated by Django 3.1.4 on 2021-01-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210104_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_tr',
            field=models.CharField(max_length=20, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_en',
            field=models.CharField(max_length=30, null=True, verbose_name='urun iceriyi'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='urun iceriyi'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_en',
            field=models.CharField(max_length=30, null=True, verbose_name='fit'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='fit'),
        ),
        migrations.AddField(
            model_name='product',
            name='sezon_en',
            field=models.CharField(max_length=30, null=True, verbose_name='sezon'),
        ),
        migrations.AddField(
            model_name='product',
            name='sezon_tr',
            field=models.CharField(max_length=30, null=True, verbose_name='sezon'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
