# Generated by Django 3.1.4 on 2021-01-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Image'),
        ),
    ]
