# Generated by Django 3.1.4 on 2021-02-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210211_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Resim'),
        ),
    ]
