# Generated by Django 3.1.4 on 2020-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('konu', 'Konu'), ('inf', 'Bilgi'), ('oner', 'Oneri'), ('shik', 'Sikayet'), ('talep', 'Talep'), ('tsk', 'Tesekkur')], max_length=255, verbose_name='subject')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('tel_number', models.CharField(max_length=20, verbose_name='telefon')),
                ('sub_subject', models.CharField(choices=[('alt konu', 'Alt Konu')], max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'contact',
            },
        ),
    ]
