# Generated by Django 3.1.4 on 2020-12-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='novu')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kategory',
                'verbose_name_plural': 'kategoriler',
                'db_table': 'category-blog',
            },
        ),
        migrations.CreateModel(
            name='Slayder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slayder_images', verbose_name='sekil')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'karusel',
                'verbose_name_plural': 'karuseller',
                'db_table': 'slayder-blog',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='adi')),
                ('image', models.ImageField(max_length=255, upload_to='blog_images', verbose_name='sekil')),
                ('discription', models.TextField(verbose_name='aciqlama')),
                ('face_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='facebook')),
                ('pint_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='pinterest')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='blog.category')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'bloglar',
                'db_table': 'blog',
            },
        ),
    ]
