# Generated by Django 3.1.4 on 2020-12-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meny',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.category')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'elave',
                'db_table': 'title',
            },
            bases=('product.category',),
        ),
    ]
