# Generated by Django 3.1.4 on 2020-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discovery_images', verbose_name='sekil')),
                ('sorgu', models.CharField(choices=[('pro', 'product'), ('catgry', 'category')], max_length=30, verbose_name='sorgu: ')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kanpanya',
                'verbose_name_plural': 'kanpanyalar',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discovery_images', verbose_name='sekil')),
                ('sorgu', models.PositiveIntegerField(choices=[('pro', 'product'), ('catgry', 'category')], verbose_name='sorgu: ')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'kesf',
                'verbose_name_plural': 'kesf et',
                'db_table': 'discovery',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='kesf')),
                ('image', models.ImageField(upload_to='discovery_images', verbose_name='sekil')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'takib',
                'verbose_name_plural': 'takibler',
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='SalesFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icon_images', verbose_name='sekil')),
                ('white_text', models.CharField(max_length=50, verbose_name='white')),
                ('red_text', models.CharField(max_length=50, verbose_name='red')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satis',
                'verbose_name_plural': 'Satis ozellikleri',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Slayder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slayder_images', verbose_name='sekil')),
                ('sorgu', models.PositiveIntegerField(choices=[('pro', 'product'), ('catgry', 'category')], verbose_name='sorgu: ')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'karusel',
                'verbose_name_plural': 'karuseller',
                'db_table': 'slayder',
            },
        ),
    ]
