# Generated by Django 3.1.4 on 2020-12-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='title',
            field=models.CharField(max_length=255, verbose_name='link'),
        ),
    ]
