# Generated by Django 3.1.4 on 2021-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='company_images', verbose_name='sekil'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='image',
            field=models.ImageField(upload_to='follow_images', verbose_name='sekil'),
        ),
    ]
