# Generated by Django 3.1.4 on 2021-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210211_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='title',
            field=models.CharField(max_length=400, verbose_name='link'),
        ),
    ]
