# Generated by Django 3.1.4 on 2021-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210214_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='image',
            field=models.CharField(max_length=400, verbose_name='sekil'),
        ),
    ]
